Fix issues #3

diff --git a/.github/workflows/dockerhub_publish.yml b/.github/workflows/dockerhub_publish.yml
--- a/.github/workflows/dockerhub_publish.yml
+++ b/.github/workflows/dockerhub_publish.yml
@@ -26,16 +26,20 @@ jobs:
     steps:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      - id: check_upstream
+      - name: Check upstream caddy version
+        id: check_upstream
         run: |
-          docker pull docker.io/library/caddy || exit 1
+          docker pull docker.io/library/caddy
           version=$(docker image inspect --format '{{json .}}' caddy | jq .RepoTags | grep -E ':[0-9]' | tr -d " \",")
+          if [ -z $version ] ; then echo "FAILED" ; exit 5 ; fi
           echo "Upstream version is ${version}"
           echo "upstream=$version" >> "$GITHUB_OUTPUT"
-      - id: check_my
+      - name: Check my caddy version
+        id: check_my
         run: |
-          docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest || exit 1
+          docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
           version=$(docker image inspect --format '{{json .}}' ${{ env.IMAGE_NAME }} | jq .RepoTags | grep -E ':[0-9]' | tr -d " \",")
+          if [ -z $version ] ; then echo "FAILED" ; exit 5 ; fi
           echo "My version is ${version}"
           echo "my=$version" >> "$GITHUB_OUTPUT"
 
